name: build_packages

on:
  pull_request:
  push:
  
jobs:
  package_builder:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        buildtype: [demo, freeware, full]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}
        
    - name: Set Git Info
      id: gitinfo
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      
    - name: Set variables
      id: vars
      run: |
        if [ "${{ matrix.buildtype }}" = "demo" ]
        then
          echo "::set-output name=cmake_build::BUILD_DEMO"
        elif [ "${{ matrix.buildtype }}" = "freeware" ]
        then
          echo "::set-output name=cmake_build::BUILD_FREEWARE"
        else
          echo "::set-output name=cmake_build::BUILD_FULL"
        fi
        
    - name: Install Dependencies
      run: |
        sudo apt-get install -qq -y nsis > /dev/null
        
    - name: Configure Vanilla Conquer Data
      run: |
        cmake -DCMAKE_BUILD_TYPE=Release -D${{ steps.vars.outputs.cmake_build }}=ON -DCMAKE_INSTALL_PREFIX=/usr -B build
        
    - name: Build Vanilla Conquer Data Packages
      run: |
        cmake --build build -- -j 4
        cd build
        cpack --config CPackConfig-TD.cmake
        cpack --config CPackConfig-RA.cmake
        LC_ALL=C cpack -G NSIS --config CPackConfig-TD.cmake
        LC_ALL=C cpack -G NSIS --config CPackConfig-RA.cmake
        
    - name: Prepare Archive Data
      run: |
        mkdir artifact
        mv ./build/vanilla-conquer-data-installer-td-${{ matrix.buildtype }}.zip artifact/
        mv ./build/vanilla-conquer-data-installer-td-${{ matrix.buildtype }}.exe artifact/
        mv ./build/vanilla-conquer-data-installer-td-${{ matrix.buildtype }}.deb artifact/
        mv ./build/vanilla-conquer-data-installer-ra-${{ matrix.buildtype }}.zip artifact/
        mv ./build/vanilla-conquer-data-installer-ra-${{ matrix.buildtype }}.exe artifact/
        mv ./build/vanilla-conquer-data-installer-ra-${{ matrix.buildtype }}.deb artifact/
        
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: vanilla-conquer-data-${{ matrix.buildtype }}
        path: artifact

  release:
    needs: package_builder
    runs-on: "ubuntu-latest"
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            vanilla-conquer-data-demo/*
            vanilla-conquer-data-freeware/*
            vanilla-conquer-data-full/*
